<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('customers')->insert([
            [
                'id' => 1,
                'name' => 'Juan, Dela Cruz',
                'email' => 'juan.delacruz@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 2,
                'name' => 'Maria O. Campo',
                'email' => 'maria.campo@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 3,
                'name' => 'Tom Cruz',
                'email' => 'tom.cruz@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 4,
                'name' => 'Romero Agusto',
                'email' => 'romero.agusto@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 5,
                'name' => 'Carlotta Monvelli',
                'email' => 'carlotta.m@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 6,
                'name' => 'Angelo Reyes',
                'email' => 'angelo.reyes@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 7,
                'name' => 'Bianca Fernandez',
                'email' => 'bianca.fernandez@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 8,
                'name' => 'Carlos Mendoza',
                'email' => 'carlos.mendoza@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 9,
                'name' => 'Diana Santos',
                'email' => 'diana.santos@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 10,
                'name' => 'Eduardo Villanueva',
                'email' => 'eduardo.villanueva@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 11,
                'name' => 'Faith Aquino',
                'email' => 'faith.aquino@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 12,
                'name' => 'Gabriel Torres',
                'email' => 'gabriel.torres@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 13,
                'name' => 'Hannah Bautista',
                'email' => 'hannah.bautista@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 14,
                'name' => 'Ivan Castillo',
                'email' => 'ivan.castillo@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 15,
                'name' => 'Jasmine Ocampo',
                'email' => 'jasmine.ocampo@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 16,
                'name' => 'Kevin Domingo',
                'email' => 'kevin.domingo@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 17,
                'name' => 'Liza Navarro',
                'email' => 'liza.navarro@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 18,
                'name' => 'Marco Salazar',
                'email' => 'marco.salazar@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 19,
                'name' => 'Nadine Pascual',
                'email' => 'nadine.pascual@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 20,
                'name' => 'Oscar Ramirez',
                'email' => 'oscar.ramirez@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 21,
                'name' => 'Patricia Lozano',
                'email' => 'patricia.lozano@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 22,
                'name' => 'Quintin Herrera',
                'email' => 'quintin.herrera@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 23,
                'name' => 'Rosanna Valdez',
                'email' => 'rosanna.valdez@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 24,
                'name' => 'Samuel Guevarra',
                'email' => 'samuel.guevarra@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 25,
                'name' => 'Teresa Marasigan',
                'email' => 'teresa.marasigan@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 26,
                'name' => 'Umberto Lacsina',
                'email' => 'umberto.lacsina@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 27,
                'name' => 'Veronica Ilagan',
                'email' => 'veronica.ilagan@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 28,
                'name' => 'Wendell Corpuz',
                'email' => 'wendell.corpuz@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 29,
                'name' => 'Ximena Padilla',
                'email' => 'ximena.padilla@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
            [
                'id' => 30,
                'name' => 'Yolanda Cabrera',
                'email' => 'yolanda.cabrera@example.com',
                'phone' => null,
                'address' => null,
                'created_at' => '2026-07-21 22:28:15',
            ],
        ]);
    }
}
