<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerTransactionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('customer_transactions')->insert([
            [
                'id' => 1,
                'customer_id' => 1,
                'order_id' => 1,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-4081',
                'payment_method' => 'Gcash',
                'amount' => 500.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:33:24',
                'updated_at' => '2026-07-22 00:46:58',
            ],
            [
                'id' => 2,
                'customer_id' => 2,
                'order_id' => 2,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-5529',
                'payment_method' => 'Maya',
                'amount' => 3850.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:33:24',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 3,
                'customer_id' => 3,
                'order_id' => 3,
                'store' => 'TikTok Shop',
                'transaction_id' => 'TXN-1102',
                'payment_method' => 'Card',
                'amount' => 2980.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:33:24',
                'updated_at' => '2026-07-22 04:41:34',
            ],
            [
                'id' => 4,
                'customer_id' => 4,
                'order_id' => 4,
                'store' => 'TikTok Shop',
                'transaction_id' => 'TXN-9021',
                'payment_method' => 'Maya',
                'amount' => 4600.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:33:24',
                'updated_at' => '2026-07-22 04:42:01',
            ],
            [
                'id' => 5,
                'customer_id' => 5,
                'order_id' => 5,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-8841',
                'payment_method' => 'COD',
                'amount' => 5200.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:33:24',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 6,
                'customer_id' => 6,
                'order_id' => 6,
                'store' => 'Shopify',
                'transaction_id' => 'TXN-6310',
                'payment_method' => 'Gcash',
                'amount' => 755.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:33:24',
                'updated_at' => '2026-07-22 04:41:54',
            ],
            [
                'id' => 7,
                'customer_id' => 7,
                'order_id' => 7,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9926',
                'payment_method' => 'Maya',
                'amount' => 500.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 8,
                'customer_id' => 8,
                'order_id' => 8,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9927',
                'payment_method' => 'Card',
                'amount' => 1450.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 9,
                'customer_id' => 9,
                'order_id' => 9,
                'store' => 'TikTok Shop',
                'transaction_id' => 'TXN-ORD-9928',
                'payment_method' => 'Gcash',
                'amount' => 750.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 10,
                'customer_id' => 10,
                'order_id' => 10,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9929',
                'payment_method' => 'Bank Transfer',
                'amount' => 2600.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 11,
                'customer_id' => 11,
                'order_id' => 11,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9930',
                'payment_method' => 'COD',
                'amount' => 2100.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 12,
                'customer_id' => 12,
                'order_id' => 12,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9931',
                'payment_method' => 'Gcash',
                'amount' => 1250.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 13,
                'customer_id' => 13,
                'order_id' => 13,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9932',
                'payment_method' => 'Maya',
                'amount' => 500.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 14,
                'customer_id' => 14,
                'order_id' => 14,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9933',
                'payment_method' => 'COD',
                'amount' => 1450.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 15,
                'customer_id' => 15,
                'order_id' => 15,
                'store' => 'Shopify',
                'transaction_id' => 'TXN-ORD-9934',
                'payment_method' => 'Bank Transfer',
                'amount' => 750.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 16,
                'customer_id' => 16,
                'order_id' => 16,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9935',
                'payment_method' => 'Maya',
                'amount' => 2100.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 17,
                'customer_id' => 17,
                'order_id' => 17,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9936',
                'payment_method' => 'COD',
                'amount' => 1950.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 18,
                'customer_id' => 18,
                'order_id' => 18,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9937',
                'payment_method' => 'Card',
                'amount' => 500.00,
                'status' => 'Error',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 19,
                'customer_id' => 19,
                'order_id' => 19,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9938',
                'payment_method' => 'Gcash',
                'amount' => 1450.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 20,
                'customer_id' => 20,
                'order_id' => 20,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9939',
                'payment_method' => 'COD',
                'amount' => 750.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 21,
                'customer_id' => 21,
                'order_id' => 21,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9940',
                'payment_method' => 'Bank Transfer',
                'amount' => 2100.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 22,
                'customer_id' => 22,
                'order_id' => 22,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9941',
                'payment_method' => 'COD',
                'amount' => 1250.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 23,
                'customer_id' => 23,
                'order_id' => 23,
                'store' => 'Shopify',
                'transaction_id' => 'TXN-ORD-9942',
                'payment_method' => 'Maya',
                'amount' => 500.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 24,
                'customer_id' => 24,
                'order_id' => 24,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9943',
                'payment_method' => 'Card',
                'amount' => 2850.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 25,
                'customer_id' => 25,
                'order_id' => 25,
                'store' => 'Shopify',
                'transaction_id' => 'TXN-ORD-9944',
                'payment_method' => 'COD',
                'amount' => 750.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 26,
                'customer_id' => 26,
                'order_id' => 26,
                'store' => 'TikTok Shop',
                'transaction_id' => 'TXN-ORD-9945',
                'payment_method' => 'Maya',
                'amount' => 1450.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 27,
                'customer_id' => 27,
                'order_id' => 27,
                'store' => 'Lazada',
                'transaction_id' => 'TXN-ORD-9946',
                'payment_method' => 'Bank Transfer',
                'amount' => 2100.00,
                'status' => 'Verified',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 28,
                'customer_id' => 28,
                'order_id' => 28,
                'store' => 'WooCommerce',
                'transaction_id' => 'TXN-ORD-9947',
                'payment_method' => 'COD',
                'amount' => 500.00,
                'status' => 'Error',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 29,
                'customer_id' => 29,
                'order_id' => 29,
                'store' => 'Shopify',
                'transaction_id' => 'TXN-ORD-9948',
                'payment_method' => 'Card',
                'amount' => 1950.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
            [
                'id' => 30,
                'customer_id' => 30,
                'order_id' => 30,
                'store' => 'TikTok Shop',
                'transaction_id' => 'TXN-ORD-9949',
                'payment_method' => 'Gcash',
                'amount' => 750.00,
                'status' => 'Pending',
                'created_at' => '2026-07-21 22:28:15',
                'updated_at' => '2026-07-22 00:33:31',
            ],
        ]);
    }
}
