<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('orders')->insert([
            [
                'id' => 1,
                'order_code' => '#ORD-9922',
                'customer_id' => 1,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1450.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Shipped',
            ],
            [
                'id' => 2,
                'order_code' => '#ORD-9922-2',
                'customer_id' => 2,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2550.00,
                'payment_method' => 'Credit/Debit Card',
                'status' => 'Pending',
            ],
            [
                'id' => 3,
                'order_code' => '#ORD-9923',
                'customer_id' => 3,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1300.00,
                'payment_method' => 'Credit/Debit Card',
                'status' => 'Shipped',
            ],
            [
                'id' => 4,
                'order_code' => '#ORD-9922-3',
                'customer_id' => 4,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2150.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Pending',
            ],
            [
                'id' => 5,
                'order_code' => '#ORD-9924',
                'customer_id' => 5,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 750.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Pending',
            ],
            [
                'id' => 6,
                'order_code' => '#ORD-9925',
                'customer_id' => 6,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2100.00,
                'payment_method' => 'GCash',
                'status' => 'Delivered',
            ],
            [
                'id' => 7,
                'order_code' => '#ORD-9926',
                'customer_id' => 7,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 500.00,
                'payment_method' => 'Maya',
                'status' => 'Pending',
            ],
            [
                'id' => 8,
                'order_code' => '#ORD-9927',
                'customer_id' => 8,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1450.00,
                'payment_method' => 'Credit/Debit Card',
                'status' => 'Shipped',
            ],
            [
                'id' => 9,
                'order_code' => '#ORD-9928',
                'customer_id' => 9,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 750.00,
                'payment_method' => 'GCash',
                'status' => 'Delivered',
            ],
            [
                'id' => 10,
                'order_code' => '#ORD-9929',
                'customer_id' => 10,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2600.00,
                'payment_method' => 'Bank Transfer',
                'status' => 'Pending',
            ],
            [
                'id' => 11,
                'order_code' => '#ORD-9930',
                'customer_id' => 11,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2100.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Delivered',
            ],
            [
                'id' => 12,
                'order_code' => '#ORD-9931',
                'customer_id' => 12,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1250.00,
                'payment_method' => 'GCash',
                'status' => 'Shipped',
            ],
            [
                'id' => 13,
                'order_code' => '#ORD-9932',
                'customer_id' => 13,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 500.00,
                'payment_method' => 'Maya',
                'status' => 'Pending',
            ],
            [
                'id' => 14,
                'order_code' => '#ORD-9933',
                'customer_id' => 14,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1450.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Delivered',
            ],
            [
                'id' => 15,
                'order_code' => '#ORD-9934',
                'customer_id' => 15,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 750.00,
                'payment_method' => 'Bank Transfer',
                'status' => 'Shipped',
            ],
            [
                'id' => 16,
                'order_code' => '#ORD-9935',
                'customer_id' => 16,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2100.00,
                'payment_method' => 'Maya',
                'status' => 'Pending',
            ],
            [
                'id' => 17,
                'order_code' => '#ORD-9936',
                'customer_id' => 17,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1950.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Delivered',
            ],
            [
                'id' => 18,
                'order_code' => '#ORD-9937',
                'customer_id' => 18,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 500.00,
                'payment_method' => 'Credit/Debit Card',
                'status' => 'Cancelled',
            ],
            [
                'id' => 19,
                'order_code' => '#ORD-9938',
                'customer_id' => 19,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1450.00,
                'payment_method' => 'GCash',
                'status' => 'Pending',
            ],
            [
                'id' => 20,
                'order_code' => '#ORD-9939',
                'customer_id' => 20,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 750.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Pending',
            ],
            [
                'id' => 21,
                'order_code' => '#ORD-9940',
                'customer_id' => 21,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2100.00,
                'payment_method' => 'Bank Transfer',
                'status' => 'Delivered',
            ],
            [
                'id' => 22,
                'order_code' => '#ORD-9941',
                'customer_id' => 22,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1250.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Shipped',
            ],
            [
                'id' => 23,
                'order_code' => '#ORD-9942',
                'customer_id' => 23,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 500.00,
                'payment_method' => 'Maya',
                'status' => 'Pending',
            ],
            [
                'id' => 24,
                'order_code' => '#ORD-9943',
                'customer_id' => 24,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2850.00,
                'payment_method' => 'Credit/Debit Card',
                'status' => 'Delivered',
            ],
            [
                'id' => 25,
                'order_code' => '#ORD-9944',
                'customer_id' => 25,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 750.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Shipped',
            ],
            [
                'id' => 26,
                'order_code' => '#ORD-9945',
                'customer_id' => 26,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1450.00,
                'payment_method' => 'Maya',
                'status' => 'Pending',
            ],
            [
                'id' => 27,
                'order_code' => '#ORD-9946',
                'customer_id' => 27,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 2100.00,
                'payment_method' => 'Bank Transfer',
                'status' => 'Delivered',
            ],
            [
                'id' => 28,
                'order_code' => '#ORD-9947',
                'customer_id' => 28,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 500.00,
                'payment_method' => 'Cash on Delivery',
                'status' => 'Cancelled',
            ],
            [
                'id' => 29,
                'order_code' => '#ORD-9948',
                'customer_id' => 29,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 1950.00,
                'payment_method' => 'Credit/Debit Card',
                'status' => 'Shipped',
            ],
            [
                'id' => 30,
                'order_code' => '#ORD-9949',
                'customer_id' => 30,
                'order_date' => '2026-07-22 06:28:15',
                'total_amount' => 750.00,
                'payment_method' => 'GCash',
                'status' => 'Pending',
            ],
        ]);
    }
}
