<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('payments')->insert([
    [
        'id' => 1,
        'order_id' => 1,
        'amount' => 1450.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 2,
        'order_id' => 2,
        'amount' => 2550.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 3,
        'order_id' => 3,
        'amount' => 1300.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 4,
        'order_id' => 4,
        'amount' => 2150.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 5,
        'order_id' => 5,
        'amount' => 750.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 6,
        'order_id' => 6,
        'amount' => 2100.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 7,
        'order_id' => 7,
        'amount' => 500.00,
        'method' => 'Cash on Delivery',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 8,
        'order_id' => 8,
        'amount' => 1450.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 9,
        'order_id' => 9,
        'amount' => 750.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 10,
        'order_id' => 10,
        'amount' => 2600.00,
        'method' => 'Bank Transfer',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 11,
        'order_id' => 11,
        'amount' => 2100.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 12,
        'order_id' => 12,
        'amount' => 1250.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 13,
        'order_id' => 13,
        'amount' => 500.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 14,
        'order_id' => 14,
        'amount' => 1450.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 15,
        'order_id' => 15,
        'amount' => 750.00,
        'method' => 'Bank Transfer',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 16,
        'order_id' => 16,
        'amount' => 2100.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 17,
        'order_id' => 17,
        'amount' => 1950.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 18,
        'order_id' => 18,
        'amount' => 500.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Refunded',
        'paid_at' => null,
    ],
    [
        'id' => 19,
        'order_id' => 19,
        'amount' => 1450.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 20,
        'order_id' => 20,
        'amount' => 750.00,
        'method' => 'Cash on Delivery',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 21,
        'order_id' => 21,
        'amount' => 2100.00,
        'method' => 'Bank Transfer',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 22,
        'order_id' => 22,
        'amount' => 1250.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 23,
        'order_id' => 23,
        'amount' => 500.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 24,
        'order_id' => 24,
        'amount' => 2850.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 25,
        'order_id' => 25,
        'amount' => 750.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 26,
        'order_id' => 26,
        'amount' => 1450.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 27,
        'order_id' => 27,
        'amount' => 2100.00,
        'method' => 'Bank Transfer',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 28,
        'order_id' => 28,
        'amount' => 500.00,
        'method' => 'Cash on Delivery',
        'status' => 'Refunded',
        'paid_at' => null,
    ],
    [
        'id' => 29,
        'order_id' => 29,
        'amount' => 1950.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 30,
        'order_id' => 30,
        'amount' => 750.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 31,
        'order_id' => 1,
        'amount' => 1450.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 32,
        'order_id' => 2,
        'amount' => 2550.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 33,
        'order_id' => 3,
        'amount' => 1300.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 34,
        'order_id' => 4,
        'amount' => 2150.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 35,
        'order_id' => 5,
        'amount' => 750.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 36,
        'order_id' => 6,
        'amount' => 2100.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 37,
        'order_id' => 7,
        'amount' => 500.00,
        'method' => 'Cash on Delivery',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 38,
        'order_id' => 8,
        'amount' => 1450.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 39,
        'order_id' => 9,
        'amount' => 750.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 40,
        'order_id' => 10,
        'amount' => 2600.00,
        'method' => 'Bank Transfer',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 41,
        'order_id' => 11,
        'amount' => 2100.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 42,
        'order_id' => 12,
        'amount' => 1250.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 43,
        'order_id' => 13,
        'amount' => 500.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 44,
        'order_id' => 14,
        'amount' => 1450.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 45,
        'order_id' => 15,
        'amount' => 750.00,
        'method' => 'Bank Transfer',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 46,
        'order_id' => 16,
        'amount' => 2100.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 47,
        'order_id' => 17,
        'amount' => 1950.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 48,
        'order_id' => 18,
        'amount' => 500.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Refunded',
        'paid_at' => null,
    ],
    [
        'id' => 49,
        'order_id' => 19,
        'amount' => 1450.00,
        'method' => 'GCash',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 50,
        'order_id' => 20,
        'amount' => 750.00,
        'method' => 'Cash on Delivery',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 51,
        'order_id' => 21,
        'amount' => 2100.00,
        'method' => 'Bank Transfer',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 52,
        'order_id' => 22,
        'amount' => 1250.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 53,
        'order_id' => 23,
        'amount' => 500.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 54,
        'order_id' => 24,
        'amount' => 2850.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 55,
        'order_id' => 25,
        'amount' => 750.00,
        'method' => 'Cash on Delivery',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 56,
        'order_id' => 26,
        'amount' => 1450.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
    [
        'id' => 57,
        'order_id' => 27,
        'amount' => 2100.00,
        'method' => 'Bank Transfer',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 58,
        'order_id' => 28,
        'amount' => 500.00,
        'method' => 'Cash on Delivery',
        'status' => 'Refunded',
        'paid_at' => null,
    ],
    [
        'id' => 59,
        'order_id' => 29,
        'amount' => 1950.00,
        'method' => 'Credit/Debit Card',
        'status' => 'Paid',
        'paid_at' => '2026-07-21 09:12:00',
    ],
    [
        'id' => 60,
        'order_id' => 30,
        'amount' => 750.00,
        'method' => 'GCash',
        'status' => 'Pending',
        'paid_at' => null,
    ],
]);
    }
}
