<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::table('products')->insert([
    [
        'sku' => 'CPU-0001',
        'product_name' => 'Ryzen 5 5600',
        'brand' => 'AMD',
        'category' => 'Processor',
        'description' => '6-Core 12-Thread Desktop Processor',
        'category_id' => 1,
        'price' => 7299.00,
        'cost' => 6500.00,
        'stock_quantity' => 25,
        'status' => 'active',
        'image_url' => 'products/ryzen5-5600.jpg',
    ],
    [
        'sku' => 'CPU-0002',
        'product_name' => 'Core i5-12400F',
        'brand' => 'Intel',
        'category' => 'Processor',
        'description' => '6-Core 12-Thread Processor',
        'category_id' => 1,
        'price' => 8999.00,
        'cost' => 7900.00,
        'stock_quantity' => 18,
        'status' => 'active',
        'image_url' => 'products/i5-12400f.jpg',
    ],
    [
        'sku' => 'GPU-0001',
        'product_name' => 'GeForce RTX 4060',
        'brand' => 'MSI',
        'category' => 'Graphics Card',
        'description' => '8GB GDDR6 Graphics Card',
        'category_id' => 2,
        'price' => 19999.00,
        'cost' => 18300.00,
        'stock_quantity' => 12,
        'status' => 'active',
        'image_url' => 'products/rtx4060.jpg',
    ],
    [
        'sku' => 'GPU-0002',
        'product_name' => 'Radeon RX 7600',
        'brand' => 'Sapphire',
        'category' => 'Graphics Card',
        'description' => '8GB GDDR6 Gaming GPU',
        'category_id' => 2,
        'price' => 17999.00,
        'cost' => 16400.00,
        'stock_quantity' => 10,
        'status' => 'active',
        'image_url' => 'products/rx7600.jpg',
    ],
    [
        'sku' => 'MB-0001',
        'product_name' => 'B550M DS3H',
        'brand' => 'Gigabyte',
        'category' => 'Motherboard',
        'description' => 'AM4 Micro ATX Motherboard',
        'category_id' => 3,
        'price' => 5299.00,
        'cost' => 4700.00,
        'stock_quantity' => 20,
        'status' => 'active',
        'image_url' => 'products/b550m.jpg',
    ],
    [
        'sku' => 'MB-0002',
        'product_name' => 'B760M Pro RS',
        'brand' => 'ASRock',
        'category' => 'Motherboard',
        'description' => 'LGA1700 DDR5 Motherboard',
        'category_id' => 3,
        'price' => 8999.00,
        'cost' => 8100.00,
        'stock_quantity' => 15,
        'status' => 'active',
        'image_url' => 'products/b760m.jpg',
    ],
    [
        'sku' => 'RAM-0001',
        'product_name' => 'Vengeance LPX 16GB DDR4',
        'brand' => 'Corsair',
        'category' => 'Memory',
        'description' => '2x8GB DDR4 3200MHz',
        'category_id' => 4,
        'price' => 2699.00,
        'cost' => 2300.00,
        'stock_quantity' => 35,
        'status' => 'active',
        'image_url' => 'products/lpx16gb.jpg',
    ],
    [
        'sku' => 'RAM-0002',
        'product_name' => 'Kingston Fury Beast 32GB DDR5',
        'brand' => 'Kingston',
        'category' => 'Memory',
        'description' => '2x16GB DDR5 5600MHz',
        'category_id' => 4,
        'price' => 6399.00,
        'cost' => 5800.00,
        'stock_quantity' => 14,
        'status' => 'active',
        'image_url' => 'products/fury32gb.jpg',
    ],
    [
        'sku' => 'SSD-0001',
        'product_name' => 'SN770 1TB NVMe SSD',
        'brand' => 'Western Digital',
        'category' => 'Storage',
        'description' => 'PCIe Gen4 NVMe SSD',
        'category_id' => 5,
        'price' => 4299.00,
        'cost' => 3900.00,
        'stock_quantity' => 22,
        'status' => 'active',
        'image_url' => 'products/sn770.jpg',
    ],
    [
        'sku' => 'SSD-0002',
        'product_name' => '870 EVO 1TB SSD',
        'brand' => 'Samsung',
        'category' => 'Storage',
        'description' => '2.5-inch SATA SSD',
        'category_id' => 5,
        'price' => 4999.00,
        'cost' => 4550.00,
        'stock_quantity' => 18,
        'status' => 'active',
        'image_url' => 'products/870evo.jpg',
    ],
    [
        'sku' => 'PSU-0001',
        'product_name' => 'CV650 650W',
        'brand' => 'Corsair',
        'category' => 'Power Supply',
        'description' => '80+ Bronze PSU',
        'category_id' => 6,
        'price' => 3499.00,
        'cost' => 3100.00,
        'stock_quantity' => 16,
        'status' => 'active',
        'image_url' => 'products/cv650.jpg',
    ],
    [
        'sku' => 'PSU-0002',
        'product_name' => 'MAG A650BN',
        'brand' => 'MSI',
        'category' => 'Power Supply',
        'description' => '650W 80+ Bronze',
        'category_id' => 6,
        'price' => 3199.00,
        'cost' => 2850.00,
        'stock_quantity' => 21,
        'status' => 'active',
        'image_url' => 'products/a650bn.jpg',
    ],
    [
        'sku' => 'CASE-0001',
        'product_name' => 'H510',
        'brand' => 'NZXT',
        'category' => 'PC Case',
        'description' => 'Mid Tower Case',
        'category_id' => 7,
        'price' => 4399.00,
        'cost' => 3900.00,
        'stock_quantity' => 8,
        'status' => 'active',
        'image_url' => 'products/h510.jpg',
    ],
    [
        'sku' => 'CASE-0002',
        'product_name' => 'CC560',
        'brand' => 'DeepCool',
        'category' => 'PC Case',
        'description' => 'ATX Mid Tower with 4 Fans',
        'category_id' => 7,
        'price' => 2999.00,
        'cost' => 2600.00,
        'stock_quantity' => 12,
        'status' => 'active',
        'image_url' => 'products/cc560.jpg',
    ],
    [
        'sku' => 'COOL-0001',
        'product_name' => 'AK400',
        'brand' => 'DeepCool',
        'category' => 'CPU Cooler',
        'description' => '120mm Air Cooler',
        'category_id' => 8,
        'price' => 1599.00,
        'cost' => 1300.00,
        'stock_quantity' => 24,
        'status' => 'active',
        'image_url' => 'products/ak400.jpg',
    ],
    [
        'sku' => 'COOL-0002',
        'product_name' => 'Hyper 212 Black',
        'brand' => 'Cooler Master',
        'category' => 'CPU Cooler',
        'description' => 'Tower Air Cooler',
        'category_id' => 8,
        'price' => 2299.00,
        'cost' => 1950.00,
        'stock_quantity' => 13,
        'status' => 'active',
        'image_url' => 'products/hyper212.jpg',
    ],
    [
        'sku' => 'GPU-0003',
        'product_name' => 'RTX 4070 SUPER',
        'brand' => 'ASUS',
        'category' => 'Graphics Card',
        'description' => '12GB GDDR6X Graphics Card',
        'category_id' => 2,
        'price' => 39999.00,
        'cost' => 37200.00,
        'stock_quantity' => 5,
        'status' => 'active',
        'image_url' => 'products/rtx4070super.jpg',
    ],
    [
        'sku' => 'SSD-0003',
        'product_name' => '980 PRO 2TB',
        'brand' => 'Samsung',
        'category' => 'Storage',
        'description' => 'PCIe Gen4 NVMe SSD',
        'category_id' => 5,
        'price' => 8499.00,
        'cost' => 7900.00,
        'stock_quantity' => 9,
        'status' => 'active',
        'image_url' => 'products/980pro2tb.jpg',
    ],
    [
        'sku' => 'RAM-0003',
        'product_name' => 'Trident Z5 RGB 32GB DDR5',
        'brand' => 'G.Skill',
        'category' => 'Memory',
        'description' => '2x16GB DDR5 6000MHz',
        'category_id' => 4,
        'price' => 7499.00,
        'cost' => 6800.00,
        'stock_quantity' => 11,
        'status' => 'active',
        'image_url' => 'products/tridentz5.jpg',
    ],
    [
        'sku' => 'CPU-0003',
        'product_name' => 'Ryzen 7 7700X',
        'brand' => 'AMD',
        'category' => 'Processor',
        'description' => '8-Core 16-Thread Desktop Processor',
        'category_id' => 1,
        'price' => 17999.00,
        'cost' => 16500.00,
        'stock_quantity' => 7,
        'status' => 'active',
        'image_url' => 'products/7700x.jpg',
    ],
]);
    }
}
